# Generated by Django 3.2.5 on 2021-09-13 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210729_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='proile_image',
            new_name='profile_image',
        ),
    ]
