# Generated by Django 3.2.5 on 2022-01-18 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_discreview'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='discreview',
            unique_together=set(),
        ),
    ]
