# Generated by Django 3.2.5 on 2022-01-20 10:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0003_alter_discreview_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionpost',
            name='body',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
