# Generated by Django 3.2.5 on 2022-01-20 11:25

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0004_discussionpost_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionpost',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
