# Generated by Django 3.2.5 on 2021-09-25 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', '-total_vote', 'title']},
        ),
    ]
